### ISSUE TITLE
Small error when browsing in tablet mode

### ISSUE THREAD

**Issue by Guisanpea** [fbnlsr/primative.net#131]
Hello. I was admiring you blog when I noticed a problem. When watching on tablet the hamburger dropdown is a bit buggy with the images I attach a file.
Nice webpage, I like it :+1: 
![screenshot from 2018-09-18 09-33-52](https://user-images.githubusercontent.com/30202718/45671657-45dc0a80-bb26-11e8-88a9-878dfc6097aa.png)

**Comment by fbnlsr** [comment]
Hey @Guisanpea thank you so much for your comment. I'll get right on it! :)

**Comment by fbnlsr** [comment]
It should deploy now. Thanks again for your feedback. 🎉
