### ISSUE TITLE
Is your theme MIT?

### ISSUE THREAD

**Issue by rdwatters** [fbnlsr/primative.net#22]
So not really an "issue." Any chance the theme is open sourced license-ish? I'd obviously change anything brand specific. Or I'd fork it and change it considerably, but I feel like it might meet many of the content needs I have for a Content Strategy site I'm building. If not, I understand completely, but I want to take this chance to say fantastic work!

**Comment by fbnlsr** [comment]
Hey Ryan,

An easier way to contact me would've been to simply send me an email 😄 

I never thought about licencing the source code for this website, but one of the reasons I let this repository public is for people to look at the code so yeah. I'm happy to see you like it. I guess as long as you do not use any of my content (that is the images/photos, blog posts, text content and branding), I'm fine with you using the code as a foundation for your site. If you can, you could always credit me somewhere. Make sure to let me know what you came up with. 😉 

Have a great day!
